# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0-37-gf86ba4c5
_src_path: ../hexdoc
author: hexdoc-dev
book_id: hexcasting:thehexbook
github_repo: hexdoc-minecraft
gradle_mod_version_key: minecraftVersion
hexdoc_mod_plugin_classname: MinecraftModPlugin
hexdoc_plugin_classname: MinecraftPlugin
java_lang:
    ext: java
    src: java
java_package: com/example/minecraft
main_branch: main
mod_display_name: Minecraft
modid: minecraft
multiloader: false
package_export_root: src/hexdoc_minecraft/_export
package_name: hexdoc-minecraft
package_slug: hexdoc_minecraft
package_src: src/hexdoc_minecraft
pages_url: https://hexdoc-dev.github.io/hexdoc-minecraft
pattern_regex: make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)
pattern_registry: registry/MinecraftPatternRegistry.java
