name: Build the web book

on:
  push:
    branches:
      - main
    tags: "*"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to generate docs from'
        type: choice
        options:
          - (same as workflow)
      release:
        description: Release this version
        type: boolean
        default: false
      update-latest:
        description: Overwrite latest (and root, if releasing)
        type: boolean
        default: true
      publish:
        description: Package index to publish to
        type: choice
        options:
          - none
          - PyPI (release)
          - TestPyPI
      segment:
        description: 'Version segment to bump with Hatch'
        type: string
        required: false

env:
  PYPI_PACKAGE: hexdoc-minecraft

permissions:
  contents: read

concurrency:
  group: hexdoc
  cancel-in-progress: false

jobs:
  hexdoc:
    uses: object-Object/hexdoc/.github/workflows/hexdoc.yml@textures
    permissions:
      contents: write
      pages: read
    secrets: inherit
    with:
      python-version: "3.11"
      release: |-
        ${{
          github.event_name == 'workflow_dispatch' && inputs.release
          || startsWith(github.event.head_commit.message, '[Release]')
          || startsWith(github.ref, 'refs/tags')
        }}
      bump-version-segment: ${{ inputs.segment }}

  publish-pypi:
    runs-on: ubuntu-latest
    needs: [hexdoc]
    if: |-
      needs.hexdoc.outputs.release == 'true' &&
      (github.event_name != 'workflow_dispatch' || inputs.publish == 'PyPI (release)')

    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.PYPI_PACKAGE }}
    permissions:
      id-token: write

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v3
        with:
          name: hexdoc-build
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
